src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Entity\CommentClient;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention la date de debut doit être au bon format")
     * @Assert\GreaterThan("today", message="La date de debut doit être ulterieure à la date d'aujourd'hui")
     * @Assert\GreaterThanOrEqual(propertyPath="ad.dateDebut", message="La date de debut doit être ulterieure à la date de debut de disponibilité de l'annonce")
     * @Assert\LessThan(propertyPath="ad.dateFin", message="La date de debut doit être antérieure à la date de fin de disponibilité de l'annonce")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention la date de remise doit être au bon format")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de remise doit être plus éloignée de la date de début")
     * @Assert\GreaterThan(propertyPath="ad.dateDebut", message="La date de remise doit être ulterieure à la date de debut de disponibilité de l'annonce")
     * @Assert\LessThanOrEqual(propertyPath="ad.dateFin", message="La date de remise doit être antérieure à la date de fin de disponibilité de l'annonce")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $confirm;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\CommentClient", mappedBy="booking", cascade={"persist", "remove"})
     */
    private $commentClient;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vuNotifClient;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vuNotifProp;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vuNotifConfirm;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Chat", mappedBy="booking")
     */
    private $chats;

    public function __construct()
    {
        $this->chats = new ArrayCollection();
    }


    /**
     * Callback appelé à chaque fois qu'on crée une réservation
     *
     * @ORM\PrePersist
     * 
     * @return void
     */
    function prePersist()
    {

        if (empty($this->confirm)) {
            $this->confirm = 0;
        }

        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        if (empty($this->amount)) {
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function isBookable()
    {
        // 1) il faut savoir les dates qui sont impossible pour l'annonce
        $notAvailableDays = $this->ad->getNotAvailableDays();
        // 2) il faut comparer les dates choisies avec les dates impossible
        $bookingDays = $this->getDays();

        // Tableau des chaines de caracters de mes journées
        $days = array_map(function ($day) {
            return $day->format('Y-m-d');
        }, $bookingDays);

        // Tableau des chaines de caracters des journées non disponibles
        $notAvailable = array_map(function ($day) {
            return $day->format('Y-m-d');
        }, $notAvailableDays);

        foreach ($days as $day) {
            if (array_search($day, $notAvailable) !== false) {
                return false;
            }
        }
        return true;
    }

    /**
     * Permet de récuperer des journées qui correspondent à ma reservation
     *
     * @return array un tableau d'objets datetime représentant les jours de la reservation
     */
    public function getDays()
    {
        $resultat = range(
            $this->getStartDate()->getTimestamp(),
            $this->getEndDate()->getTimestamp(),
            24 * 60 * 60
        );
        $days = array_map(function ($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getConfirm(): ?int
    {
        return $this->confirm;
    }

    public function setConfirm(?int $confirm): self
    {
        $this->confirm = $confirm;

        return $this;
    }

    public function __toString()
    {
        $i = $this->id . "";
        return $i;
    }

    public function delete()
    {
        $this->setConfirm(-1);
    }

    public function getCommentClient(): ?CommentClient
    {
        return $this->commentClient;
    }

    public function setCommentClient(CommentClient $commentClient): self
    {
        $this->commentClient = $commentClient;

        // set the owning side of the relation if necessary
        if ($commentClient->getBooking() !== $this) {
            $commentClient->setBooking($this);
        }

        return $this;
    }

    public function getVuNotifClient(): ?bool
    {
        return $this->vuNotifClient;
    }

    public function setVuNotifClient(bool $vuNotifClient): self
    {
        $this->vuNotifClient = $vuNotifClient;

        return $this;
    }

    public function getVuNotifProp(): ?bool
    {
        return $this->vuNotifProp;
    }

    public function setVuNotifProp(bool $vuNotifProp): self
    {
        $this->vuNotifProp = $vuNotifProp;

        return $this;
    }

    public function getVuNotifConfirm(): ?bool
    {
        return $this->vuNotifConfirm;
    }

    public function setVuNotifConfirm(bool $vuNotifConfirm): self
    {
        $this->vuNotifConfirm = $vuNotifConfirm;

        return $this;
    }

    /**
     * @return Collection|Chat[]
     */
    public function getChats(): Collection
    {
        return $this->chats;
    }

    public function addChat(Chat $chat): self
    {
        if (!$this->chats->contains($chat)) {
            $this->chats[] = $chat;
            $chat->setBooking($this);
        }

        return $this;
    }

    public function removeChat(Chat $chat): self
    {
        if ($this->chats->contains($chat)) {
            $this->chats->removeElement($chat);
            // set the owning side to null (unless already changed)
            if ($chat->getBooking() === $this) {
                $chat->setBooking(null);
            }
        }

        return $this;
    }
}

src/Entity/Chat.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ChatRepository")
 */
class Chat
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Booking", inversedBy="chats")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booking;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="chats")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Author;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $seen;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sendTo;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooking(): ?Booking
    {
        return $this->booking;
    }

    public function setBooking(?Booking $booking): self
    {
        $this->booking = $booking;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getSeen(): ?bool
    {
        return $this->seen;
    }

    public function setSeen(bool $seen): self
    {
        $this->seen = $seen;

        return $this;
    }

    public function getSendTo(): ?User
    {
        return $this->sendTo;
    }

    public function setSendTo(?User $sendTo): self
    {
        $this->sendTo = $sendTo;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType
{
    private $transformer;

    public function __construct(FrenchToDateTimeTransformer $transformer)
    {
        $this->transformer = $transformer;
    }


    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate', TextType::class, $this->getConfiguration("Date de reservation", "La date à laquelle vous comptez louer le bien"))
            ->add('comment', TextareaType::class, $this->getConfiguration(false, "Si vous avez un commentaire, n'hésitez pas à en faire part !", [
                "required" => false
            ]))
            ->add('endDate', TextType::class, $this->getConfiguration("Date de remise", "La date à laquelle vous retournez le bien"));

        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce : {{ ad.title }}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous" />
{% endblock %}

{% block body %}

        <div class="bradcam_area breadcam_bg_2">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text text-center">
                        <h3>Reserver</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
        {% include 'partials/message.html.twig' %}

    <div class="container" id="body">
        <h2>Réservez pour l'annonce : {{ ad.title }}</h2>
        <p>Vous êtes sur le point de reserver le bien de <strong>{{ ad.author.fullName }}</strong>, dites nous tout on s'occupe du reste !</p>
    
        {{ form_start(form) }}
        <div class="alert alert-light">
            <h4>Commencez par nous dire quelles sont les dates qui vous intérsessent</h4>
            <div class="row">
                <div class="col">
                    {{ form_row(form.startDate)}}
                </div>
                <div class="col">
                    {{ form_row(form.endDate)}}
                </div>
            </div>
            <h4>Montant du sejour : <span id="amount"></span> Dhs</h4>
            <span id="days">0</span> jours(s) à {{ ad.price }}/jour
            <h4 class="mt-3">Vous avez un commentaire ?</h4>
            {{ form_row(form.comment) }}
        </div>

        <h4>Vous avez terminé !</h4>

        <button type="submit" class="btn btn-success">Je réserve !</button>

        {{ form_end(form)}}
    </div>

{% endblock %}

{% block javascripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha256-bqVeqGdJ7h/lYPq6xrPv/YGzMEb6dNxlfiTUHSgRCp8=" crossorigin="anonymous"></script>
<script>
    $(document).ready(function(){
        {% for day in ad.notAvailableDays %}
            {% if loop.first %}
                var date = new Date("{{ day.format('Y/m/d') }}");
                date.setDate(date.getDate() + 1 );
            {% else %}
                var dateEnd = new Date("{{ day.format('Y/m/d') }}");
                dateEnd.setDate(dateEnd.getDate() + 1 );
                if(date < dateEnd){
                    date = dateEnd;
                }
            {% endif %}
        {% endfor %}
        if(typeof date !== 'undefined'){
            const ye = new Intl.DateTimeFormat('en', { year: 'numeric' }).format(date)
            const mo = new Intl.DateTimeFormat('en', { month: '2-digit' }).format(date)
            const da = new Intl.DateTimeFormat('en', { day: '2-digit' }).format(date)
            date = `${da}/${mo}/${ye}`;
        }
            
            var startDate = "{{ ad.dateDebut.format('Y/m/d') }}";
            var endDate = "{{ ad.dateFin.format('Y/m/d') }}";
            startDate = new Date(startDate);
            endDate = new Date(endDate);
            endDateInf = new Date("{{ ad.dateFin.format('Y/m/d') }}");
            startDateSup = new Date();
            endDateInf.setDate(endDateInf.getDate() - 1);
            startDateSup.setDate(startDate.getDate() + 1);
            if(startDate > new Date((new Date()).valueOf() + 1000*3600*24)){
                $('#booking_startDate').datepicker({
                    format: 'dd/mm/yyyy',
                    datesDisabled: [
                        {% for day in ad.notAvailableDays %}
                            "{{ day.format('d/m/Y') }}",
                        {% endfor %}
                    ],
                    startDate: startDate,
                    endDate: endDateInf
                    
                });
                if(typeof date !== 'undefined'){
                    $('#booking_endDate').datepicker({
                        format: 'dd/mm/yyyy',
                        datesDisabled: [
                            {% for day in ad.notAvailableDays %}
                                "{{ day.format('d/m/Y') }}",
                            {% endfor %}
                            date
                        ],
                        startDate: startDateSup,
                        endDate: endDate
                    });     
                }else{
                    $('#booking_endDate').datepicker({
                        format: 'dd/mm/yyyy',
                        datesDisabled: [
                            {% for day in ad.notAvailableDays %}
                                "{{ day.format('d/m/Y') }}",
                            {% endfor %}
                        ],
                        startDate: startDateSup,
                        endDate: endDate
                    }); 
                }
            }else{
                $('#booking_startDate').datepicker({
                    format: 'dd/mm/yyyy',
                    datesDisabled: [
                        {% for day in ad.notAvailableDays %}
                            "{{ day.format('d/m/Y') }}",
                        {% endfor %}
                    ],
                    startDate: new Date((new Date()).valueOf() + 1000*3600*24),
                    endDate : endDateInf
                });
                if(typeof date !== 'undefined'){
                    $('#booking_endDate').datepicker({
                        format: 'dd/mm/yyyy',
                        datesDisabled: [
                            {% for day in ad.notAvailableDays %}
                                "{{ day.format('d/m/Y') }}",
                            {% endfor %}
                            date
                        ],
                        startDate: new Date((new Date()).valueOf() + 1000*3600*24*2),
                        endDate : endDate
                    });     
                }else{
                    $('#booking_endDate').datepicker({
                        format: 'dd/mm/yyyy',
                        datesDisabled: [
                            {% for day in ad.notAvailableDays %}
                                "{{ day.format('d/m/Y') }}",
                            {% endfor %}
                        ],
                        startDate: new Date((new Date()).valueOf() + 1000*3600*24*2),
                        endDate : endDate
                    }); 
                }
            }
        
        $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
    })
    function calculateAmount() {
        const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
        const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
        if(endDate && startDate && endDate > startDate)
        {   
            const DAY_TIME = 24 * 60 * 60 *1000;
            const interval = endDate.getTime() - startDate.getTime();
            const days = interval / DAY_TIME;
            const amount = days * {{ ad.price }};
            $('#days').text(days);
            $('#amount').text(amount.toLocaleString('fr-FR'));
        }
    }
</script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n°{{ booking.id }}{% endblock %}


{% block body %}
            <div class="bradcam_area breadcam_bg_2">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text text-center">
                        <h3>Votre réservation (n°{{ booking.id }})</h3>
                        <h2 style="color : white">
                            {% if booking.confirm == 1 %}
                                Cette reservation a été confirméé par son proprietaire
                            {% else %}
                                Cette reservation est en attente de confirmation par son proprietaire
                            {% endif %}
                        </h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% set ad = booking.ad %}
    {% set author = ad.author %}

    <div class="container" id="body">
        <h1></h1>

        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <h4 class="alert-heading">Bravo !</h4>
                <p>
                    Votre résevation auprés de 
                    <strong><a href="{{ path('user_show', {'id': author.id, 'slug' : author.slug}) }}">{{ author.fullName }}</a></strong>
                    pour l'annonce
                    <strong><a href="{{ path('ads_show', {'id': ad.id, 'slug' : ad.slug}) }}">{{ ad.title }}</a></strong>
                    a bien été prise en compte !
                </p>
            </div>
        {% endif %}

        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Détails</h2>
                    <dl class="row">
                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{ booking.id }}</dd>
                        <dt class="col-md-4">Date de début</dt>
                        <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Date de remise</dt>
                        <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Nombre de jours</dt>
                        <dd class="col-md-8">{{ booking.duration }}</dd>
                        <dt class="col-md-4">Montant total</dt>
                        <dd class="col-md-8">{{ booking.amount }} Dhs</dd>
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{ booking.comment | default('Aucun commentaire') }}</dd>
                    </dl>

                    <hr>

                    <h2 class="alert-heading">Le propriétaire</h2>
                    <div class="row mb-3">
                        <div class="col-3">
                            <img src="{{ author.picture }}" class="avatar avatar-medium" alt="Avatar de {{ author.fullName }}">
                        </div>
                        <div class="col">
                            <h4>
                                <a href="{{ path('user_show', {'id': author.id, 'slug' : author.slug}) }}">{{ author.fullName }}</a>
                                {% if booking.endDate > date() and booking.confirm == 1 %}
                                    <a class="genric-btn info  circle" href="/chat/{{ booking.id }}"><i class="fas fa-check-circle"></i>Discuter</a>
                                {% endif %}
                            </h4>
                            <span class="badge badge-primary" style="background: #f44a40;">{{ author.ads|length }} annonces</span>
                        </div>
                    </div>
                    {{ author.description|raw }}

                    <a href="{{ path('user_show', {'id': author.id, 'slug' : author.slug}) }}" class="btn genric-btn danger circle arrow">Plus d'infos sur {{ author.firstName }}</a>
                </div>
                <div class="alert alert-light" id="comment">
                    <h2 class="alert-heading">Votre avis compte !</h2>
                        {% if booking.confirm == 0 %}
                           <p>Cette reservation est en attente de confirmation par son proprietaire...</p>

                        {% else %}
                            
                            {% if date() > date(booking.endDate) %}
                                {% set comment = booking.ad.commentFromAuthor(app.user) %}
                                {% if comment is not null %}
                                    <blockquote>{{ comment.content | raw}}</blockquote>

                                    <strong>Note :</strong> {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                                {% else %}
                                    {{ form_start(form) }}
                                    <div  style="padding-bottom:20px;">
                                        {{ form_widget(form.rating, {'attr': {'id': 'rating', 'oninput':'rating()'}}) }}
                                    </div>
                                    {{ form_widget(form.rating, {'attr': {'class': 'task_field'}}) }}
                                    <div style="padding-bottom:20px;">
                                        <a style="width:100%" class="btn genric-btn danger-border   arrow" onclick="article()">Commentaire pour l'article  loué: </a> <br>
                                        <div id="article" style="display:none;">
                                            {{form_row(form.positiveComment) }}
                                            {{form_row(form.negativeComment) }}
                                         </div>
                                    </div>
                                   <div style="padding-bottom:20px;">
                                     <a style="width:100%" class="btn genric-btn danger-border  arrow" onclick="proprietaire()">Commentaire pour le Proprietaire de l'objet: </a>
                                        <div id="proprietaire" style="display:none;">
                                            {{ form_widget(form)}}
                                        </div>
                                   </div>
                                    <button type="submit" style="width:100%" class="btn genric-btn danger">Confirmer</button>
                                    {{ form_end(form) }}
                                {% endif %}
                            {% else %}
                                <p>Vous ne pourrez pas noter cette annonce tant que votre location ne sera pas complete !</p>
                            {% endif %}
                                    
                        {% endif %}
                </div>
            </div>
            <div class="col">
                <div class="alert alert-light">
                    <h2 class="alert-heading">Votre article</h2>

                    <h4>
                        <a href="{{ path('ads_show', {'id': ad.id, 'slug' : ad.slug}) }}">{{ ad.title }}</a>
                    </h4>
                    <img src="{{ ad.coverImage }}" alt="Image de {{ ad.title }}" class="img-fluid">
                    {{ ad.content | raw }}

                    <a href="{{ path('ads_show', {'id': ad.id, 'slug' : ad.slug}) }}" class="btn genric-btn danger circle arrow">Plus d'informations</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
     <script>
        function proprietaire() {
        var x = document.getElementById("proprietaire");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
        }
        
        function article() {
        var x = document.getElementById("article");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
        }
        
     </script>
{% endblock %}