src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\DBAL\Types\BooleanType;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverImage;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SubCategory", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank(message="Vous devez choisir une catégorie")
     */
    private $subCategory;




    /**
     * @var integer
     */
    private $premiumValue;

    /**
     * @var string
     */
    private $premiumDuration;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\City", inversedBy="ads")
     */
    private $cities;

    /**
     * @ORM\Column(type="boolean")
     */
    private $blackListed;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention la date de debut doit être au bon format")
     * @Assert\GreaterThan("today", message="La date de debut de disponibilité doit être ulterieure à la date d'aujourd'hui")
     */
    private $dateDebut;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\Date(message="Attention la date de fin de disponibilité doit être au bon format")
     * @Assert\GreaterThan(propertyPath="dateDebut", message="La date de fin de disponibilité doit être plus éloignée de la date de début")
     */
    private $dateFin;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->cities = new ArrayCollection();
    }

    /**
     * permet d'initialiser le slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify;
            $this->slug = $slugify->slugify($this->title);
        }
        if (empty($this->blackListed)) {
            $this->blackListed = 0;
        }
    }



    /**
     * Permet de récuperer le commentaire d'un auteur par rapport à une annonce
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments as $comment) {
            if ($comment->getAuthor() === $author) {
                return $comment;
            }
        }
        return null;
    }


    /**
     * Permet d'obtenir la moyenne globale des notes pour cette annonce
     *
     * @return float
     */
    public function getAvgRatings()
    {
        //calculer la somme des notations
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment) {
            return $total + $comment->getRating();
        }, 0);
        //faire la division pour avoir la moyenne
        if (count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }

    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette annonce
     *
     * @return array
     */
    public function getNotAvailableDays()
    {
        $notAvailableDays = [];

        foreach ($this->bookings as $booking) {
            if ($booking->getConfirm()) {
                //Calculer les jours qio existent entre la date d'arrivée et de départ
                $resultat = range(
                    $booking->getStartDate()->getTimestamp(),
                    $booking->getEndDate()->getTimestamp(),
                    24 * 60 * 60
                );
                $days = array_map(function ($dayTimestamp) {
                    return new \DateTime(date('Y-m-d', $dayTimestamp));
                }, $resultat);

                $notAvailableDays = array_merge($notAvailableDays, $days);
            } else {
                continue;
            }
        }

        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPremiumValue()
    {
        return $this->premiumValue;
    }

    public function setPremiumValue(bool $premiumValue): self
    {
        $this->premiumValue = $premiumValue;

        return $this;
    }

    public function getPremiumDuration()
    {
        return $this->premiumDuration;
    }

    public function setPremiumDuration(string $premiumDuration): self
    {
        $this->premiumDuration = $premiumDuration;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }

    public function getSubCategory(): ?SubCategory
    {
        return $this->subCategory;
    }

    public function setSubCategory(?SubCategory $subCategory): self
    {
        $this->subCategory = $subCategory;

        return $this;
    }

    /**
     * @return Collection|City[]
     */
    public function getCities(): Collection
    {
        return $this->cities;
    }

    public function addCity(City $city): self
    {
        if (!$this->cities->contains($city)) {
            $this->cities[] = $city;
        }

        return $this;
    }

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Form\AdType;
use App\Entity\Image;
use App\Entity\Filter;
use App\Entity\Premium;
use App\Form\FilterType;
use App\Repository\AdRepository;
use App\Repository\CityRepository;
use App\Repository\CategoryRepository;
use App\Repository\PremiumRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\SubCategoryRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\Pagination\PaginationInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdController extends AbstractController
{
    /**
     * @Route("/ads", name="ads_index")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request, AdRepository $repo, PremiumRepository $premiumRepository, EntityManagerInterface $manager): Response
    {
        $filter = new Filter();
        $form = $this->createForm(FilterType::class, $filter);
        $form->handleRequest($request);
        $premiums = $premiumRepository->findFilter($filter);
        $ads = array();
        foreach ($premiums as $premium) {
            $ad = $premium->getAd();
            if ($premium->getValue()) {
                $ad->setPremiumValue(true);
            }
            $ads[] = $ad;
        }
        foreach ($ads as $ad) {
            $dates = $ad->getNotAvailableDays();
            $dateStart = \DateTime::createFromFormat('d/m/Y', $filter->getStartDate());
            $dateEnd = \DateTime::createFromFormat('d/m/Y', $filter->getEndDate());
            foreach ($dates as $date) {
                if ($date >= $dateStart && $date <= $dateEnd) {
                    $key = array_search($ad, $ads, true);
                    unset($ads[$key]);
                    break;
                }
            }
        }

        $ads = $paginator->paginate(
            $ads,
            $request->query->getInt('page', 1),
            6 //nombre d'annoces
        );


        return $this->render('ad/index.html.twig', [
            'ads' => $ads,
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet de communiquer à ajax les sous-catégories d'une catégorie aprés avoir reçu son titre
     * 
     * @Route("/ads/subCategory", name="ads_subCategory")
     *
     * @param Request $resquest
     * @param SubCategoryRepository $repo
     * @return Response
     */
    public function getSubCategoriesByCategory(Request $request, SubCategoryRepository $subRepo, CategoryRepository $catRepo): Response
    {
        $postData = json_decode($request->getContent());
        $categoryTitle = $postData->category;
        $subCategoryArray = [];
        $category = $catRepo->findOneByTitle($categoryTitle);
        $subCategories = $category->getSubCategories();
        foreach ($subCategories as $subCategory) {
            $subCategoryArray[] = [
                'id' => $subCategory->getId(),
                'title' => $subCategory->getTitle()
            ];
        }
        return $this->json($subCategoryArray, 200);
    }

    /**
     * permet de créer une annonce
     * 
     * @Route("/ads/new", name="ads_create")
     * @IsGranted("ROLE_USER")
     *
     * @return Response
     */
    function create(Request $request, EntityManagerInterface $manager, CityRepository $cityRepository)
    {
        $ad = new Ad;

        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $startDate = new \DateTime();
            $premium = new Premium;
            if ($ad->getPremiumValue()) {
                $premium->setValue($ad->getPremiumValue())
                    ->setStartDate($startDate)
                    ->setEndDate((clone $startDate)->modify('+' . $ad->getPremiumDuration() . ' days'))
                    ->setAd($ad);
            } else {
                $premium->setValue($ad->getPremiumValue())
                    ->setAd($ad);
            }
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }

            $ad->setAuthor($this->getUser());

            $manager->persist($premium);
            $city = $cityRepository->findOneByName("Tout Le maroc");
            $ad->addCity($city);
            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été enregistrée"
            );

            return $this->redirectToRoute('ads_show', [
                'id' => $ad->getId(),
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * permet d'editer une annonce
     * 
     * @Route("/ads/{id}/{slug}/edit", name="ads_edit")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier")
     *
     * @return Response
     */
    function edit(Ad $ad, Request $request, EntityManagerInterface $manager)
    {
        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été modifiée"
            );

            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/edit.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }


    /**
     * permet d'afficher une seule annonce
     *
     * @Route("/ads/{id}/{slug}", name="ads_show")
     * 
     * @return Response
     */
    function show(Ad $ad)
    {
        return $this->render('ad/show.html.twig', [
            "ad" => $ad
        ]);
    }

    /**
     * Permet de supprimer une annonce
     * 
     * @Route("/ads/{id}/{slug}/delete", name="ads_delete")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la supprimer")
     *
     * @return Response
     */
    function delete(Ad $ad, EntityManagerInterface $manager)
    {
        $ad->setBlackListed(true);
        $manager->persist($ad);
        $manager->flush();

        $this->addFlash(
            'success',
            "L'annonce <strong>{$ad->getTitle()}</strong> a bien été supprimée"
        );

        return $this->redirectToRoute("ads_index");
    }
}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'id' : ad.id, 'slug' : ad.slug}) %}
    
<div class="col-md-4 annonce">
    <div class="card bg-light md-3">
        <div class="card-header text-center">
            <strong>{{ ad.price }}Dhs / jour</strong> <br>
            {% if ad.comments|length > 0 %}
            {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings } %}
            {% else %}
            <small>Pas encore noté</small>
            {% endif %}
                {% if premium == 1 %}
                    <h5><i class="fas fa-medal"></i> PREMIUM</h5>
                {% endif %}
                
        </div>
        <a href="{{ url }}">
            <img src="{{ ad.coverImage }}" alt="image de l'objet" style="height: 200px; width: 100%; display: block">
        </a>
        <div class="card-body">
            <a href="{{ url }}">
                <h4 class="card-title">{{ ad.title }}</h4>
            </a>
            <p class="card-text"> {{ ad.introduction }} </p>
            <div class="button-group-area mt-10">
            <a href="{{ url }}" class="genric-btn danger circle">En savoir plus</a>

            {% if app.user and app.user == ad.author %}
        
                <a href="{{ path('ads_edit', {'id': ad.id, 'slug': ad.slug }) }}" class="genric-btn danger-border circle">Modifier l'annonce</a>
            {% endif %}
            </div>
        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{% block _ad_images_widget %}

    <input type="hidden" id="widgets-counter" value="0">

    <p>Ici vous pouvez ajouter vos propres images</p>

    {{ form_widget(form) }}

    <div class="form-group">
        <button type="button" id="add_image" class="btn btn-secondary">Ajouter une image</button>
    </div>
{% endblock %}

{% block _ad_images_entry_widget %}
    <div class="form-group" id="block_{{id}}">
        <div class="row">
            <div class="col-md-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-md-2"> 
                <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}


         <div class="bradcam_area breadcam_bg_2">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text text-center">
                        <h3>Modifier l'annonce : {{ ad.title }}</h3>
                    </div>
                </div>
            </div>
        </div>
       </div>  

    <div class="container">
        <h1>Modifier l'annonce : {{ ad.title }}</h1>

        {{ form_start(form) }}

        {{ form_widget(form) }}
         

        <button type="submit "class="btn btn-primary">Enregistrer les modifications</button>

        {{ form_end(form) }}
    </div>

{% endblock %}

{% block javascripts %}

<script src="/js/ad.js"></script>

{% endblock %}

templates/ad/show.html.twig
  
{% extends 'base.html.twig' %}

{% block title %}
{{ ad.title }}
{% endblock %}

{% block stylesheets %}
<style>

    .desc .masquer {
        display:none;
    }
    .desc:hover .masquer {
        display: block;
    }
    .bg-image {
        /* The image used */
        background-image: url("photographer.jpg");
        /* Add the blur effect */
        filter: blur(8px);
        -webkit-filter: blur(8px);
        /* Full height */
        height: 100%;
        /* Center and scale the image nicely */
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }
    /* Position text in the middle of the page/image */
    .bg-text {
        background-color: rgb(0, 0, 0);
        /* Fallback color */
        background-color: rgba(0, 0, 0, 0.4);
        /* Black w/opacity/see-through */
        color: white;
        font-weight: bold;
        border: 3px solid #f1f1f1;
        text-align: center;
    }
</style>
{% endblock %}

{% block body %}

<div class="bradcam_area breadcam_bg_2" style=" padding-bottom: 15px;">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text text-center">
                    <div class="container-fluid " id="ad-title-container" style="background-image: url({{ ad.coverImage }})">
                        <div class="bg-image"></div>
                        <div class="container bg-text">
                            <h1>{{ ad.title }}</h1>
                            <p id="ad-introduction">{{ ad.introduction }}</p>
                            <p class="h2">
                                <strong>{{ ad.price }} Dhs</strong> par jour
                            </p>

                            {% if app.user and app.user == ad.author %}
                            <a href="{{ path('ads_edit', {'id': ad.id, 'slug': ad.slug }) }}" class="btn genric-btn primary">Modifier l'annonce</a>
                            <a href="{{ path('ads_delete', {'id': ad.id, 'slug': ad.slug }) }}" class="btn genric-btn danger" onclick="return confirm(`Êtes-vous sûr de vouloir supprimer l'annonce : {{ ad.title }} ?`)">Supprimer l'annonce</a>
                            {% else %}
                            <a href="{{ path('booking_create', {'id': ad.id, 'slug' : ad.slug }) }}" class="btn genric-btn danger"> Réserver</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    {% include 'partials/message.html.twig' %}



<div class="container" id="body">
    <div class="row">
        <div class="col-md-8 mb-3">
            <div class="feature-img">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for image in ad.images %}
                    {% if loop.first %}
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    {% else %}
                    <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}"></li>
                    {% endif %}
                    {% endfor %}
                </ol>
                <div class="carousel-inner">
                    {% for image in ad.images %}
                    <div class="carousel-item {% if loop.first %} active {% endif %}">
                        <img class="d-block w-100" src="{{ image.url }}" alt="First slide">
                        <div class="carousel-caption d-none d-md-block">
                            <p> {{ image.caption }} </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
                </div>
            </div>
            <div class="blog_details">
            <h2>{{ ad.title }} </h2>
             <p class="excert">{{ ad.content | raw }}</p>
            
            </div>

                        


            <hr>

            {% if ad.comments | length > 0 %}
            <h2 class="mb-3">Commentaires :</h2>
            <div class="alert alert-info">
                <h4 class="alert-heading text-center">
                    <div class="row align-items-center">
                        <div class="col">
                            Note globale donnée par nos clients
                        </div>
                        <div class="col">
                            {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings } %}
                            <br>
                            <small>(calculée sur {{ ad.comments | length }} avis)</small>
                        </div>
                    </div>
                </h4>
            </div>
            {% for comment in ad.comments %}

            <div class="comment-list" style="padding-bottom:20px">
                <div class="single-comment justify-content-between d-flex">
                    <div class="user justify-content-between d-flex">
                        <div class="thumb" style="padding-right:10px"> <a href="{{path('user_show', {'id': comment.author.id, 'slug': comment.author.slug})}}"> 
                            <img class="avatar avatar-medium" src="{{comment.author.picture}}" alt="">
                         </a>  </div>
                        <div class="desc">
                             <h5>
                                <a href="{{path('user_show', {'id': comment.author.id, 'slug': comment.author.slug})}}">{{ comment.author.firstName }} {{ comment.author.lastName }} :  </a>
                            </h5>
                            <p class="comment "> {{ comment.content | raw }} </p>
                             <div class="d-flex justify-content-between">
                                 <div class="d-flex align-items-center">
                                    <p class="date"><strong>la note de </strong>
                                     {% include 'partials/rating.html.twig' with {'rating': comment.rating } %}</p>
                                 </div>

                              </div>
                        </div>
                    </div>
                </div>
               
            </div>
            {% endfor %}
            {% else %}
            <h2>Cette annonce n'a pas encore reçu de commentaires</h2>
            {% endif %}
        </div>
        <div class="col">
            {% set a = ad.author %}
            <div class="row">
                <div class="col-3">
                    <a href="{{path('user_show', {'id': a.id, 'slug': a.slug})}}">
                        <img src="{{a.picture}}" class="avatar avatar-medium" alt="Avatar de {{a.fullName}}">
                    </a>
                </div>
                <div class="col">
                    <a href="{{path('user_show', {'id': a.id, 'slug': a.slug})}}">
                        <h3>{{a.fullName}}</h3>
                    </a>
                    <span class="badge badge-primary" style="background: #f44a40;">{{a.ads | length}} annonces</span>
                </div>
            </div>
            {{a.introduction | raw}}
            {% if ad.comments | length > 0 %}
            <h2 class="mb-3">Commentaires :</h2>
            <div class="alert alert-info">
                <h4 class="alert-heading text-center">
                    <div class="row align-items-center">
                        <div class="col">
                            Note globale donnée par nos clients
                        </div>
                        <div class="col">
                            {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings } %}
                            <br>
                            <small >(calculée sur {{ ad.comments | length }} avis)</small>
                        </div>
                    </div>
                </h4>
            </div>

               {% for comment in ad.comments %}

            <div class="comment-list" style="padding-bottom:20px">
                <div class="single-comment justify-content-between d-flex">
                    <div class="user justify-content-between d-flex">
                        <div class="thumb" style="padding-right:10px"> 
                            <a href="{{path('user_show', {'id': comment.author.id, 'slug': comment.author.slug})}}"> 
                                <img class="avatar avatar-medium" src="{{comment.author.picture}}" alt="">
                            </a>
                        </div>
                        <div class="desc">
                             <h5>
                                <a href="{{path('user_show', {'id': comment.author.id, 'slug': comment.author.slug})}}">{{ comment.author.firstName }} {{ comment.author.lastName }} :  </a>
                            </h5>
                            <p class="comment masquer"> {{ comment.proContent | raw }} </p>
                            <div class="d-flex justify-content-between">
                                <div class="d-flex align-items-center">
                                    <p class="date"><strong>la note de </strong>
                                    {% include 'partials/rating.html.twig' with {'rating': comment.rating } %}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
             {% else %}
            <h4>Ce proprietaire n'a pas encore reçu de commentaires</h4>
            {% endif %}
        </div>
        
    </div>
</div>
{% endblock %}